2019-08-09 21:22:24,213 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-09 21:28:15,113 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-09 21:31:58,270 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-09 21:50:17,158 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-09 21:57:34,209 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-09 21:58:51,147 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-09 23:29:52,645 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-09 23:51:52,211 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-10 00:00:20,277 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-10 00:02:12,673 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:43]
2019-08-10 08:57:09,318 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:45]
2019-08-10 09:06:34,347 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:45]
2019-08-10 11:12:00,908 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:45]
2019-08-10 13:51:48,014 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:45]
2019-08-10 13:52:14,080 ERROR: Exception on /reset_password_request [GET] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/app/routes.py", line 89, in reset_password_request
    if current_user.is_autenticated:
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'is_autenticated'
2019-08-10 13:54:10,754 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:45]
2019-08-10 13:59:12,442 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MywiZXhwIjoxNTY1NDM1MjM5LjY1ODU0Njd9.JCr2hxgZBnvJRazqGhKBDRZvcdMNqAhY2Ninhgnn9To [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/app/routes.py", line 111, in reset_password
    db.session.commite()
AttributeError: 'scoped_session' object has no attribute 'commite'
2019-08-10 14:02:03,203 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MywiZXhwIjoxNTY1NDM1NDc1LjgyNzY5NTR9.cwDwekAQBodXpK7xZ-DMv6YcdcgR0OpOO2FqEbMN1gc [POST] [in /home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alexey/PycharmProjects/flask_site/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/alexey/PycharmProjects/flask_site/app/routes.py", line 111, in reset_password
    db.session.commit()
AttributeError: 'scoped_session' object has no attribute 'commite'
2019-08-10 14:02:33,748 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:45]
2019-08-10 22:24:37,015 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:47]
2019-08-10 22:33:29,230 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:47]
2019-08-10 22:42:42,462 INFO: Microblog startup [in /home/alexey/PycharmProjects/flask_site/app/__init__.py:47]
